"""Added play_count attribute to Puzzle to track how many users have submitted a score to it.

Revision ID: 392cc3ab727e
Revises: d36fe864aab7
Create Date: 2024-04-30 20:29:40.648226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392cc3ab727e'
down_revision = 'd36fe864aab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))

    op.execute("UPDATE Puzzles SET play_count = (SELECT COUNT(*) FROM Leaderboard WHERE Puzzles.id=Leaderboard.puzzleID)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Puzzles', schema=None) as batch_op:
        batch_op.drop_column('play_count')

    # ### end Alembic commands ###
