"""empty message

Revision ID: a90c7a8f4860
Revises: 
Create Date: 2024-04-25 23:00:49.036696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90c7a8f4860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Followers',
    sa.Column('followerID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followerID'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('followerID', 'userID')
    )
    op.create_table('Puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('creatorID', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creatorID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Leaderboard',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('puzzleID', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('dateSubmitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puzzleID'], ['Puzzles.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('userID', 'puzzleID')
    )
    op.create_table('Ratings',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('puzzleID', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('dateRated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puzzleID'], ['Puzzles.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('userID', 'puzzleID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ratings')
    op.drop_table('Leaderboard')
    op.drop_table('Puzzles')
    op.drop_table('Followers')
    op.drop_table('Users')
    # ### end Alembic commands ###
